### ISSUE TITLE
App scaffolding

### ISSUE THREAD

**Issue by kevinccbsg** [guidesmiths/mentoring-app-restaurants-reviews#1]
Create App application:

- [x] Discuss what should we use (SSR or CSR)
- [x] State management tool. Do we need it?
- [x] Install cypress. Should we use it in the same project?

**Comment by danielherrerohernando** [comment]
Regarding the topics to be discussed, I think we can go for CSR, for managing the state I guess it would be enough with React Hooks, however as I have used Hooks before I prefer to work here with Redux.
And for the installation of cypress, I´d like to do it in the same project but in a different project (the way you did with Iñigo).
@kevinccbsg ❤️

**Comment by kevinccbsg** [comment]
We can close this ticket 👍 I will create a different one for the cypress setup 😃
