### ISSUE TITLE
How to integrate Systemic with a frontend APP

### ISSUE THREAD

**Issue by kevinccbsg** [guidesmiths/mentoring-app-restaurants-reviews#2]
Discuss how to integrate systemic in a frontend app.

- [x] Review advantajes
- [x] Check how to send ENV variables

**Comment by danielherrerohernando** [comment]
I´ve already used systemic to serve microfrontends so the integration part and env variables are pretty clear.

**Comment by kevinccbsg** [comment]
This PR https://github.com/guidesmiths/mentoring-app-restaurants-reviews/pull/4 closes this issue. Good job 👍
