### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by kevinccbsg** [guidesmiths/mentoring-app-restaurants-reviews#3]
We have to decide a way to deploy this application.

Which one is a good option Serverless, Heroku, GitHub pages, zsh, from scratch...

**Comment by danielherrerohernando** [comment]
I´ll deploy it to Heroku. We need the app´s tiny API running to call back-end services so static hosting like GitHub pages is not suitable.

**Comment by danielherrerohernando** [comment]
I´ve already deployed it to Heroku using Github actions to build the Docker image and push it to Heroku container registry. Then Heroku runs the container and serves the app in https://matteoaffinity.herokuapp.com/
@kevinccbsg

**Comment by kevinccbsg** [comment]
Oh, amazing! I usually deploy it without Docker, just the server using the Heroku CD. We have to catch up next week. Using Github actions it is very interesting KS!!!

**Comment by kevinccbsg** [comment]
> I´ll deploy it to Heroku. We need the app´s tiny API running to call back-end services so static hosting like GitHub pages is not suitable.
That's absolutely right

**Comment by danielherrerohernando** [comment]
It´s already deployed via Travis to Heroku container registry
